#!/usr/bin/env ruby

`git rev-parse --show-toplevel >/dev/null 2>/dev/null`
exit 1 unless $?.success?
ref=nil
tags={}
logs=`git log --pretty=format:"%H@@@%ad@@@%s@@@%D"`.split ?\n
logs.map{_1.split"@@@"}.each{|c|
ref = c[-1] unless c[3].nil?
tags[ref] = tags[ref].nil? ? [c[0,3]] : tags[ref] + [c[0,3]]
}
puts "# Changelog\n\n"
tags.each{|k, v|
  hash, ts, msg = v[0].map(&:strip)
  if k =~ /^tag: /
    tag_name = $'.strip
    prev_tag_name = (
         tags.keys[tags.keys.index(k) + 1] ||= tags.values[-1][-1][0]
         ).sub("tag: ", "")
    puts "## version [#{tag_name}](../../releases/tag/#{tag_name}) " +
         "in #{ts} ([compare](../../compare/#{prev_tag_name}...#{tag_name}))"
  else
    next
  end
  puts
  v.each{|hash, ts, msg|
    puts <<~A
    - [#{hash}](../../commit/#{hash})
      - #{msg}
    A
  }
  puts
}
